baseurl = "https://www.franks.codes/"
languageCode = "en-us"
title = "Franks.codes"
canonifyurls = true
publishdir = "../frne.github.io"
theme = "beautifulhugo"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  subtitle = "My two cents about programming, systems and the internet"
  author = "Frank Neff"

[Author]
    name = "Frank Neff"
    bio = "Frank Neff is a full time coder in love with the JVM. Doing eHealth systems in Java, he likes secure software that performs. Open minded, with a passion in object oriented & functional programming, he is always interested in new ideas and technology."
    github = "frne"
    twitter = "frank_neff"
    linkedin = "frankneff"
    stackoverflow = "users/1045760/frank-neff"
[[menu.main]]
    name = "categories"
    weight = 1
    identifier = "categories"
    url = "/categories"

[[menu.main]]
    name = "tags"
    weight = 2
    identifier = "tags"
    url = "/tags"

[[menu.main]]
    name = "source"
    weight = 3
    identifier = "source"
    url = "https://github.com/frne/blog"